// Copyright (c) 2026 Softside Tech Pty Ltd. All rights reserved.
// SPDX-License-Identifier: MPL-2.0

//! Raw FFI bindings to Haivision libsrt v1.5.6.
//!
//! This crate provides unsafe bindings generated by bindgen. All public
//! API is unsafe C FFI. Higher-level safe wrappers live in `srt-transport`.
//!
//! # Initialization
//!
//! libsrt requires a global `srt_startup()` / `srt_cleanup()` lifecycle.
//! Use [`ensure_initialized()`] to guarantee it's called exactly once per process.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

use std::sync::OnceLock;

/// RAII guard for libsrt global initialization.
///
/// Calls `srt_startup()` on creation and `srt_cleanup()` on drop.
/// Only one instance should exist per process (enforced by [`ensure_initialized`]).
struct SrtStartup;

impl SrtStartup {
    fn new() -> Self {
        let ret = unsafe { srt_startup() };
        assert!(ret == 0, "srt_startup() failed with code {ret}");
        SrtStartup
    }
}

impl Drop for SrtStartup {
    fn drop(&mut self) {
        unsafe {
            srt_cleanup();
        }
    }
}

static SRT_INIT: OnceLock<SrtStartup> = OnceLock::new();

/// Ensure libsrt is initialized. Safe to call multiple times — initialization
/// happens exactly once per process.
pub fn ensure_initialized() {
    SRT_INIT.get_or_init(SrtStartup::new);
}

// ── Convenience re-exports with short names ──
// Bindgen prefixes enum constants with their type name. These aliases
// provide the natural C names used in documentation and examples.

// Socket status
pub const SRTS_INIT: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_INIT;
pub const SRTS_OPENED: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_OPENED;
pub const SRTS_LISTENING: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_LISTENING;
pub const SRTS_CONNECTING: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_CONNECTING;
pub const SRTS_CONNECTED: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_CONNECTED;
pub const SRTS_BROKEN: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_BROKEN;
pub const SRTS_CLOSING: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_CLOSING;
pub const SRTS_CLOSED: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_CLOSED;
pub const SRTS_NONEXIST: SRT_SOCKSTATUS = SRT_SOCKSTATUS_SRTS_NONEXIST;

// Socket options
pub const SRTO_MSS: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_MSS;
pub const SRTO_SNDSYN: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_SNDSYN;
pub const SRTO_RCVSYN: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_RCVSYN;
pub const SRTO_FC: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_FC;
pub const SRTO_SNDBUF: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_SNDBUF;
pub const SRTO_RCVBUF: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_RCVBUF;
pub const SRTO_RENDEZVOUS: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_RENDEZVOUS;
pub const SRTO_MAXBW: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_MAXBW;
pub const SRTO_LATENCY: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_LATENCY;
pub const SRTO_INPUTBW: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_INPUTBW;
pub const SRTO_OHEADBW: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_OHEADBW;
pub const SRTO_PASSPHRASE: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_PASSPHRASE;
pub const SRTO_PBKEYLEN: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_PBKEYLEN;
pub const SRTO_IPTTL: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_IPTTL;
pub const SRTO_IPTOS: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_IPTOS;
pub const SRTO_TLPKTDROP: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_TLPKTDROP;
pub const SRTO_SNDDROPDELAY: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_SNDDROPDELAY;
pub const SRTO_CONNTIMEO: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_CONNTIMEO;
pub const SRTO_LOSSMAXTTL: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_LOSSMAXTTL;
pub const SRTO_RCVLATENCY: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_RCVLATENCY;
pub const SRTO_PEERLATENCY: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_PEERLATENCY;
pub const SRTO_STREAMID: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_STREAMID;
pub const SRTO_PAYLOADSIZE: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_PAYLOADSIZE;
pub const SRTO_TRANSTYPE: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_TRANSTYPE;
pub const SRTO_KMREFRESHRATE: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_KMREFRESHRATE;
pub const SRTO_KMPREANNOUNCE: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_KMPREANNOUNCE;
pub const SRTO_ENFORCEDENCRYPTION: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_ENFORCEDENCRYPTION;
pub const SRTO_PEERIDLETIMEO: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_PEERIDLETIMEO;
pub const SRTO_GROUPCONNECT: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_GROUPCONNECT;
pub const SRTO_PACKETFILTER: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_PACKETFILTER;
pub const SRTO_RETRANSMITALGO: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_RETRANSMITALGO;

// SRTO_CRYPTOMODE and SRTO_MAXREXMITBW are behind ENABLE_AEAD_API_PREVIEW.
// They may or may not be present depending on the build. Define as raw values.
pub const SRTO_CRYPTOMODE: SRT_SOCKOPT = 62;
pub const SRTO_MAXREXMITBW: SRT_SOCKOPT = 63;

// Transport types
pub const SRTT_LIVE: SRT_TRANSTYPE = SRT_TRANSTYPE_SRTT_LIVE;
pub const SRTT_FILE: SRT_TRANSTYPE = SRT_TRANSTYPE_SRTT_FILE;

// Epoll events
pub const SRT_EPOLL_IN: SRT_EPOLL_OPT = SRT_EPOLL_OPT_SRT_EPOLL_IN;
pub const SRT_EPOLL_OUT: SRT_EPOLL_OPT = SRT_EPOLL_OPT_SRT_EPOLL_OUT;
pub const SRT_EPOLL_ERR: SRT_EPOLL_OPT = SRT_EPOLL_OPT_SRT_EPOLL_ERR;
pub const SRT_EPOLL_CONNECT: SRT_EPOLL_OPT = SRT_EPOLL_OPT_SRT_EPOLL_CONNECT;
pub const SRT_EPOLL_ET: SRT_EPOLL_OPT = SRT_EPOLL_OPT_SRT_EPOLL_ET;

// Socket options (recv buffer query)
pub const SRTO_RCVDATA: SRT_SOCKOPT = SRT_SOCKOPT_SRTO_RCVDATA;

// Epoll flags
pub const SRT_EPOLL_ENABLE_EMPTY: SRT_EPOLL_FLAGS =
    SRT_EPOLL_FLAGS_SRT_EPOLL_ENABLE_EMPTY;

// Group types
pub const SRT_GTYPE_BROADCAST: SRT_GROUP_TYPE = SRT_GROUP_TYPE_SRT_GTYPE_BROADCAST;
pub const SRT_GTYPE_BACKUP: SRT_GROUP_TYPE = SRT_GROUP_TYPE_SRT_GTYPE_BACKUP;

/// Helper: get the last SRT error code.
pub fn last_error_code() -> i32 {
    unsafe { srt_getlasterror(std::ptr::null_mut()) }
}

/// Helper: get the last SRT error message as a Rust string.
pub fn last_error_message() -> String {
    let ptr = unsafe { srt_getlasterror_str() };
    if ptr.is_null() {
        return String::from("unknown error");
    }
    unsafe { std::ffi::CStr::from_ptr(ptr) }
        .to_string_lossy()
        .into_owned()
}
